### ISSUE TITLE
Is it possible to remove reliance on Client ID and Client Secret?

### ISSUE THREAD

**Issue by alex-mcla** [DynamicsNinja/FlowExecutionHistory#2]
Hi Ivan

Thanks for this new tool!

When opening the tool with one of my connections, I get an error "This tool is using server to server connection to get Power Automate flow runs. Please use connecitons that is authenticated with client ID and client secret."

Is this essential, or would it be possible to use the tool using other connection methods?

Many thanks, Alex

**Comment by DynamicsNinja** [comment]
If we want to keep a seamless experience we need to use client/secret authentication, otherwise, you would get a popup for login every single time when you open the tool.

Client/secret authorization for integrations is essential on every big project so I don't feel it's a big overhead if you need to use this type of connection nowadays.

Will do a research and check how integrate other login methods, but without ruining the UX of the tool.

**Comment by alex-mcla** [comment]
Thanks for the rapid reply.

This may just be my misunderstanding of how the Flow Execution History tool works differently from other tools in the XrmToolBox for it's connection to Dataverse / integration with Dataverse. The In-App Notification Builder for example doesn't require this.

**Comment by DynamicsNinja** [comment]
Now I see what bothers you, but the data about flow runs is fetched by Power Automate API which is not fetching data from Datavserse so the normal connection is not enough.

Flow API access token needs to be fetched before executing API calls and the best way to do it is by client/secret which is already there in the connection that way user is not bothered by additional login popups.

**Comment by alex-mcla** [comment]
Thanks for explaining that! Please feel free to close this issue.

**Comment by DynamicsNinja** [comment]
I've published a new release where you can authenticate against Power Automate with username and password if you don't want to use client and secret.
